### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by AdamYLiang** [byoo24/Jamify#2]
- [x] Should have timestamps for create/update

**Playlists**
- [x] Should have a foreign key to reference creator of playlist

**Albums**
- [x] Should have a foreign key to reference author 

**Tracks** 
- [x] Should have foreign keys to reference the author as well as the album it belongs to 
- [x] Consider renaming to songs since some songs do not belong to an album 

We can cut down the join tables if we make more foreign keys. With these changes the main join table that we need will be one between playlists/songs and songs/genres. I would table followers and genres for a bonus.

Let me know if you have any questions!

**Comment by byoo24** [comment]
Refactored the Schema

**Comment by byoo24** [comment]
You can close it :D

**Comment by AdamYLiang** [comment]
Looks good, thanks!
