### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by AdamYLiang** [byoo24/Jamify#3]
**Users**
- [x] Current logged in user is `25` so there should be corresponding user with id `25`

**Playlists**
- [x] Consider storing `user_id` for user authored playlists

**Songs**
- [x] `album` should point to an `album_id` in the state
- [x] `artist` should point to an `artist_id` in the state 

**Misc**
- [x] Should also have a slice of state for `albums`
- [x] Should also have a slice of state for `artists` 
- [x] Consider having a separate slice of state outside of entities for the current song being played

Let me know if you have any questions or want to talk about these.

**Comment by byoo24** [comment]
Refactored

**Comment by byoo24** [comment]
You can close it :D

**Comment by AdamYLiang** [comment]
Nicely done!
